export const sections = {
	ourStory: {
		id: 'our-story',
		title: 'Our story',
		body: "Life really does turn on a dime… on December 4th, 2023 we received a diagnosis that we suspected and feared - Jeff had been diagnosed with ALS. For those unfamiliar, ALS is a progressive neuro-degenerative disease. It can rob you of your mobility, your ability to speak and eat, and eventually your ability to breathe. There is no cure. Only 20% of people diagnosed with ALS are still alive 3 years after symptom onset. Jeff's symptoms began almost 3.5 years ago - he's already beating the odds! Although we are devastated, we draw strength from our family and friends, and of course, our faith. Jeff is such a strong witness to the goodness of God. He immediately started making plans for how he could use his circumstance for the better, to help others, and to be an example of a life well lived. He wants to raise funds to help others with ALS, and we have started the Jeffrey F. Birkel Foundation to fundraise for the ALS Association, ALS United, and ALS Research.\n\nAnd we need your help!\n\nJeff was an avid distance runner. He's run 10 marathons and one Grand Canyon Rim to Rim (which is even longer and has a 10,000ft elevation change). In 2005, Jeff ran the Boston Marathon and helped raise funds for MPD research, a rare disease with which a dear friend and co-worker had been diagnosed.\n\nNow Jeff wants to turn his diagnosis into an opportunity to raise funds for ALS, which, like MPD, is rare and under-funded. Jeff encouraged his two boys, Matt and Mike, to take up running at a young age - and they did! They both ran Boston in 2023, and on Father’s Day of 2024 they decided they'd like to try to run it again with Jeff - one of them pushing him in a racing pushchair and the other running alongside. The Boston Marathon requires setting an acceptable qualifying time at another marathon to get an entry, so they've decided their qualifying race will be the Nebraska State Fair Marathon on August 24th."
	},
	whyDonate: {
		id: 'why-donate',
		title: 'Why donate?',
		body: "Since all funds raised by the Jeffrey F. Birkel Foundation will eventually be donated to either ALS United or the ALS Association, you might be wondering: why not donate to those charities directly? Well, if Matt and Mike qualify for the Boston Marathon, we'll still need to apply for a separate pushchair entry. To get a charitable bib entry, we'll likely need to raise over $20,000 by November. Time is precious; though we've set our sights on Boston 2024, donating to the Jeffrey F. Birkel Foundation allows us to save up and try again in 2025 if we fail to get a bib this year. In addition, incorporating as a 501(c)(3) non-profit corporation ensures all your donations will be tax-exempt and meet the requirements of companies with matching gift programs."
	},
	whatIsALS: {
		id: 'what-is-als',
		title: 'What is ALS?',
		body: "Amyotrophic lateral sclerosis, also known as motor neuron disease (MND) or Lou Gehrig's disease in the United States, is a rare, terminal neurodegenerative disorder that results in the progressive loss of both upper and lower motor neurons that normally control voluntary muscle contraction. ALS often presents in its early stages with gradual muscle stiffness, twitches, weakness, and wasting. Motor neuron loss typically continues until the abilities to eat, speak, move, and, lastly, breathe are all lost. While only 15% of people with ALS also fully develop frontotemporal dementia, an estimated 50% face at least some minor difficulties with thinking and behavior.\n\nThere is no known cure for ALS. The goal of treatment is to slow the disease progression, and improve symptoms. The disease can affect people of any age, but usually starts around the age of 60. The average survival from onset to death is two to four years, though this can vary, and about 10% of those affected survive longer than ten years."
	}
};
