name: update insta.json

on:
  schedule:
    - cron: '0 9-22 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update insta.json
        run: curl -s -X GET "https://graph.facebook.com/v22.0/17841472361745279/media?fields=caption%2Clike_count%2Cmedia_url%2Cmedia_type%2Cthumbnail_url%2Ctimestamp%2Cpermalink%2Cchildren%7Bmedia_url%7D&access_token=${{ secrets.INSTAGRAM_ACCESS_TOKEN }}" > src/insta.json

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update insta.json
          file_pattern: src/insta.json
